version: '3'
services:

  rkworkbench:
    image: "andorsk/rk_workbench:0.0.2"
    container_name: "rkworkbench"
    environment:
      AUTHENTICATE_VIA_JUPYTER: "mytoken"
    volumes:
      - "../:/workspace/"
    command:
      - '--shm-size 512m'
    restart: unless-stopped
    ports:
     - "8881:8080"

